# Generated by Django 4.0.1 on 2022-01-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('descr', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=100)),
                ('imageTitle', models.CharField(max_length=100)),
                ('trailer', models.BooleanField()),
                ('video', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('isSeries', models.BooleanField()),
            ],
        ),
    ]
